language: csharp
mono: none
dotnet: 8.0
os:
  - linux
  - osx
  - windows

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

script:
  - cd src/ContainerFileSystemWatcher/ContainerFileSystemWatcher
  - dotnet build ContainerFileSystemWatcher.csproj
  - cd ../ContainerFileSystemWatcherTests
  - dotnet build ContainerFileSystemWatcherTests.csproj
  - dotnet test ContainerFileSystemWatcherTests.csproj
