language: csharp
mono: none
dotnet: 3.1
os: linux

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

install:
  - wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
  - chmod +x ./dotnet-install.sh
  - ./dotnet-install.sh -c 8.0 --install-dir $HOME/dotnet
  - ./dotnet-install.sh -c 3.1 --install-dir $HOME/dotnet
  - export PATH=$PATH:$HOME/dotnet

script:
  - dotnet build src/ContainerFileSystemWatcher/ContainerFileSystemWatcher/ContainerFileSystemWatcher.csproj
  - dotnet build src/ContainerFileSystemWatcher/ContainerFileSystemWatcherTests/ContainerFileSystemWatcherTests.csproj
  - dotnet build src/ContainerFileSystemWatcher/ContainerFileSystemWatcher.demo/ContainerFileSystemWatcher.demo.csproj
  - dotnet build src/ContainerFileSystemWatcher/ContainerFileSystemWatcher.ConsoleApp/ContainerFileSystemWatcher.ConsoleApp.csproj
  - dotnet test src/ContainerFileSystemWatcher/ContainerFileSystemWatcherTests/ContainerFileSystemWatcherTests.csproj
