language: csharp
mono: none
dotnet: 5.0
script:
  - cd src/ContainerFileSystemWatcher/ContainerFileSystemWatcher
  - dotnet build ContainerFileSystemWatcher.csproj
  - cd ../ContainerFileSystemWatcherTests
  - dotnet build ContainerFileSystemWatcherTests.csproj
  - dotnet test ContainerFileSystemWatcherTests.csproj
