language: csharp
mono: none
os:
  - linux
  - osx
  - windows

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x ./dotnet-install.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dotnet-install.sh -c 8.0 --install-dir $HOME/dotnet; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dotnet-install.sh -c 3.1 --install-dir $HOME/dotnet; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=$PATH:$HOME/dotnet; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod +x ./dotnet-install.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./dotnet-install.sh -c 8.0 --install-dir $HOME/dotnet; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./dotnet-install.sh -c 3.1 --install-dir $HOME/dotnet; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=$PATH:$HOME/dotnet; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install dotnetcore-sdk --version 8.0; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install dotnetcore-sdk --version 3.1.419; fi

script:
  - dotnet build src/ContainerFileSystemWatcher/ContainerFileSystemWatcher/ContainerFileSystemWatcher.csproj
  - dotnet build src/ContainerFileSystemWatcher/ContainerFileSystemWatcherTests/ContainerFileSystemWatcherTests.csproj
  - dotnet build src/ContainerFileSystemWatcher/ContainerFileSystemWatcher.demo/ContainerFileSystemWatcher.demo.csproj
  - dotnet build src/ContainerFileSystemWatcher/ContainerFileSystemWatcher.ConsoleApp/ContainerFileSystemWatcher.ConsoleApp.csproj
  - dotnet test src/ContainerFileSystemWatcher/ContainerFileSystemWatcherTests/ContainerFileSystemWatcherTests.csproj
