language: csharp
mono: none
dotnet: 2.0
os:
  - linux
  - osx
  - windows

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

script:
  - cd src/ContainerFileSystemWatcher/ContainerFileSystemWatcher
  - dotnet restore
  - dotnet build --configuration Release
  - cd ../ContainerFileSystemWatcherTests
  - dotnet restore
  - dotnet build --configuration Release
