language: csharp
mono: none
os:
  - linux
  - osx
  - windows

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x ./dotnet-install.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dotnet-install.sh -c 7.0 --install-dir $HOME/dotnet; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=$PATH:$HOME/dotnet; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod +x ./dotnet-install.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./dotnet-install.sh -c 7.0 --install-dir $HOME/dotnet; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=$PATH:$HOME/dotnet; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install dotnetcore-sdk --version 7.0; fi

script:
  - cd src/ContainerFileSystemWatcher/ContainerFileSystemWatcher
  - dotnet build ContainerFileSystemWatcher.csproj
  - cd ../ContainerFileSystemWatcherTests
  - dotnet build ContainerFileSystemWatcherTests.csproj
  - dotnet test ContainerFileSystemWatcherTests.csproj
