language: csharp
mono: none
dotnet: 5.0
os: 
  - linux
  - osx
  - windows

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

script:
  - cd src/ContainerFileSystemWatcher/ContainerFileSystemWatcher
  - dotnet restore
  - dotnet build --configuration Release
  - dotnet test --configuration Release
